### PR TITLE
Add .editorconfig for consistent style and imports

### PR DESCRIPTION
**Pull request by nikammerlaan**
My other PR wanted to change a bunch of the imports and stuff, so I figured it'd be a good idea to have a style config for this repo.

### CODE REVIEW

**Comment by topi314** [comment]
I'm a fan of the 2 spaces, I'd rather use what lavalink uses, but that would also mean reformatting the whole thing which I don't like

**Comment by nikammerlaan** [comment]
Yeah, I don't like 2 spaces either. I'd be in favor of an autoformat to push it to 4 spaces, but this is a step in the right direction I think.

**Review by topi314 — DISMISSED** [review]

**Review by freyacodes — COMMENTED** [review]
I think in any case we should get an IDE to reformat the entire codebase if we set standards like these

**Review by topi314 — APPROVED** [review]
I think we should add more stricter rules, but this is a good baseline

**Pull request merged**
