### PR TITLE
cleanup lavaplayer fork

### PR DESCRIPTION
**Pull request by topi314**
* remove lavaplayer node & stream-merged
* add github actions
* configure new maven repos

### CODE REVIEW

**Comment by freyacodes** [comment]
Wouldn't it be better to publish to central?

**Comment by topi314** [comment]
that would be awesome, I haven't got it to work with lavalink so I didn't even try here

**Comment by freyacodes** [comment]
I think we should aim towards that. If you would like to take the initiative to set up things here, I can try troubleshooting

**Comment by topi314** [comment]
lavaplayer is now being published to https://maven.arbjerg.dev & https://s01.oss.sonatype.org
for pushing to maven central you need to hit the release button in sonatype

**Review by nikammerlaan — APPROVED** [review]

**Review by Devoxin — APPROVED** [review]

**Pull request merged**
