### PR TITLE
Video returned by YouTube isn't what was requested

### PR DESCRIPTION
**Pull request by Kamilake**
WARNING: This PR does not solve the underlying problem. Please test or reference only instead of merging this  
  

Two mornings ago, YouTube was patched to redirect all video requests playing on older Android players to restricted channels. To fix that I did a patch like this PR and for now it seems to be working fine. I don't know how to fix the root problem, but I hope my fix will help resolve this pressing issue.

https://github.com/lavalink-devs/Lavalink/issues/1030

### CODE REVIEW

**Review by IoIxD — APPROVED** [review]
Compiled Lavalink from source with this as a dependency, can confirm Youtube playback works again.

**Comment by Kamilake** [comment]
> Compiled Lavalink from source with this as a dependency, can confirm Youtube playback works again.

I don't know anything about Lavalink, and I've only used Lavaplayer myself. But if that helps, I'll try that!

**Comment by frankfraynk** [comment]
> Compiled Lavalink from source with this as a dependency, can confirm Youtube playback works again.

I'm sorry if this is uncouth, can you give a small tutorial or summary of the steps you took to achieve this?

**Comment by Kamilake** [comment]
> I'm sorry if this is uncouth, can you give a small tutorial or summary of the steps you took to achieve this?

It looks like this will help you!

```gradle
repositories {
  maven { url "https://jitpack.io" }
}
dependencies {
  implementation 'com.github.kamilake:lavaplayer:main-SNAPSHOT'
}
```

**Comment by IoIxD** [comment]
> > Compiled Lavalink from source with this as a dependency, can confirm Youtube playback works again.
> 
> I'm sorry if this is uncouth, can you give a small tutorial or summary of the steps you took to achieve this?

i have a patch file for the Lavalink repo here
https://cdn.discordapp.com/attachments/1211003213248069632/1223485274340986920/usecomm.patch?ex=661a0674&is=66079174&hm=7559ca70ac270e3e0429475847ec63b47caa9f866d1385af82c68b47d5acb730&

Apply this then run `gradlew.bat build` (windows) or `./gradlew build` (the rest of the world) from a terminal to compile

**Comment by IoIxD** [comment]
Somebody also just made a repo with that patch applied.
https://github.com/ZeyoYT/Lavalink

**Comment by frankfraynk** [comment]
there's probably a youtube rep in here just jottin' down notes...

**Comment by Kamilake** [comment]
https://github.com/lavalink-devs/lavaplayer/pull/86

Some people here used iOS (like yt-dlp) instead of WEB. It looks better this way

**Comment by devoxin** [comment]
Did you test this at all with playlists? Because during my testing, I'm getting playlists with zero tracks and a `null` title

**Comment by devoxin** [comment]
I'll be closing this regardless as I'm working on a robust implementation with retry mechanisms in place to reduce error rates. Looking to have a test build out later.

**Comment by KiterWork** [comment]
> Did you test this at all with playlists? Because during my testing, I'm getting playlists with zero tracks and a `null` title

When requesting a playlist it returns 

```
{
  loadType: 'PLAYLIST_LOADED',
  exception: null,
  pluginInfo: {},
  tracks: [
    //list of all tracks with all info correctly displayed
   ],
   playlist: {
    name: 'Newest Playlist',
    selectedTrack: null,
    author: null,
    thumbnail: null,
    uri: null,
    duration: 105171375
  }

**Comment by devoxin** [comment]
> > Did you test this at all with playlists? Because during my testing, I'm getting playlists with zero tracks and a `null` title
> 
> When requesting a playlist it returns
> ...


Cannot reproduce.
image

**Comment by KiterWork** [comment]
I got this error while trying to request a spotify url/playlist from the lavalink server (using lavalink v3)

**Comment by IziPeezeLemonSqueeze** [comment]
> Somebody also just made a repo with that patch applied. https://github.com/ZeyoYT/Lavalink

How to use this repo on maven project?

**Pull request closed without merging**
